// PDF Generator utility for trip itineraries
// Uses browser's built-in printing functionality to generate PDF

export function generateTripPDF(trip) {
  // Create a printable HTML document
  const printWindow = window.open('', '_blank');
  
  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${trip.destination || 'Trip'} Itinerary</title>
        <style>
          @media print {
            @page {
              margin: 1cm;
            }
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #667eea;
          }
          .header h1 {
            color: #667eea;
            margin: 0 0 10px 0;
            font-size: 2em;
          }
          .header .meta {
            color: #666;
            font-size: 1.1em;
          }
          .day {
            margin-bottom: 25px;
            page-break-inside: avoid;
          }
          .day-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 12px 16px;
            border-radius: 8px;
            font-weight: 600;
            font-size: 1.1em;
            margin-bottom: 10px;
          }
          .activities {
            list-style: none;
            padding: 0;
            margin: 0;
          }
          .activity {
            padding: 8px 0;
            border-bottom: 1px solid #eee;
            padding-left: 20px;
            position: relative;
          }
          .activity:before {
            content: "✓";
            position: absolute;
            left: 0;
            color: #667eea;
            font-weight: bold;
          }
          .activity:last-child {
            border-bottom: none;
          }
          .no-activities {
            color: #999;
            font-style: italic;
            padding: 10px 0;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #eee;
            text-align: center;
            color: #999;
            font-size: 0.9em;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${escapeHtml(trip.destination || 'Trip Itinerary')}</h1>
          <div class="meta">
            ${trip.startDate || '—'} ${trip.endDate ? ` - ${trip.endDate}` : ''}
          </div>
        </div>
        
        ${(trip.days || []).map((day, index) => `
          <div class="day">
            <div class="day-header">
              ${day.date || `Day ${index + 1}`}
            </div>
            ${(day.activities || []).length > 0 ? `
              <ul class="activities">
                ${day.activities.map(activity => `
                  <li class="activity">${escapeHtml(activity)}</li>
                `).join('')}
              </ul>
            ` : `
              <div class="no-activities">No activities planned for this day</div>
            `}
          </div>
        `).join('')}
        
        <div class="footer">
          Generated by TripMate - ${new Date().toLocaleDateString()}
        </div>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load, then trigger print
  setTimeout(() => {
    printWindow.print();
  }, 250);
}

function escapeHtml(text) {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

